{"link": "http://www.iana.org/domains/reserved", "appearences": 0}
{"link": "http://www.iana.org/", "appearences": 1}
{"link": "http://www.iana.org/about/excellence", "appearences": 0}
{"link": "https://pti.icann.org/", "appearences": 3}
{"link": "http://www.iana.org/reviews", "appearences": 0}
{"link": "http://www.iana.org/performance", "appearences": 0}
{"link": "https://www.icann.org/privacy/tos", "appearences": 46}
{"link": "http://www.iana.org/reports", "appearences": 0}
{"link": "http://www.iana.org/about/presentations", "appearences": 0}
{"link": "https://www.icann.org/privacy/policy", "appearences": 45}
{"link": "http://www.iana.org/time-zones", "appearences": 0}
{"link": "https://www.icann.org/", "appearences": 0}
{"link": "http://www.iana.org/abuse", "appearences": 0}
{"link": "http://www.iana.org/dnssec/tcrs", "appearences": 0}
{"link": "https://www.icann.org/en/registry-agreements", "appearences": 0}
{"link": "http://www.iana.org/dnssec/ceremonies", "appearences": 0}
{"link": "https://www.icann.org/resources/pages/idn-2012-02-25-en", "appearences": 0}
{"link": "http://www.iana.org/dnssec/files", "appearences": 0}
{"link": "http://www.iana.org/dnssec", "appearences": 3}
{"link": "http://www.iana.org/domains/idn-tables", "appearences": 0}
{"link": "http://www.iana.org/domains/arpa", "appearences": 0}
{"link": "http://www.iana.org/domains/int/policy", "appearences": 0}
{"link": "http://www.iana.org/domains/int/manage", "appearences": 0}
{"link": "http://www.iana.org/domains/int", "appearences": 0}
{"link": "http://www.iana.org/domains/root/servers", "appearences": 0}
{"link": "http://www.iana.org/domains/root/help", "appearences": 0}
{"link": "http://www.iana.org/domains/root/manage", "appearences": 0}
{"link": "http://www.iana.org/domains/root/files", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db", "appearences": 3}
{"link": "http://www.iana.org/domains/root", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--hlcj6aya9esc7a.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--zckzah.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--deba0ad.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--9t4b11yi5a.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--jxalpdlp.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--11b5bs3a9aj6g.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--80akhbyknj4f.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--g6w251d.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--0zwm56d.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--hgbk6aj7f53bba.html", "appearences": 0}
{"link": "http://www.iana.org/domains/root/db/xn--kgbechtv.html", "appearences": 0}
{"link": "http://www.iana.org/about", "appearences": 0}
{"link": "http://www.iana.org/protocols", "appearences": 1}
{"link": "http://www.iana.org/numbers", "appearences": 1}
{"link": "http://www.iana.org/domains", "appearences": 1}
{"link": "http://www.iana.org/contact", "appearences": 0}
{"link": "https://www.iana.org/dnssec/archive", "appearences": 0}
{"link": "https://www.iana.org/dnssec/procedures", "appearences": 0}
{"link": "http://www.iana.org/help/idn-repository-procedure", "appearences": 0}
{"link": "http://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml", "appearences": 0}
